[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.29"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
  "forge-std/=lib/forge-std/src/",
  "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]
